

INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (2,'B101','工程量统计','ConsturctionManager.UI.FrmConstructionQuantity','B1','打开工程量统计窗体')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (3,'B10101','工程量统计新增','ConsturctionManager.UI.FrmConstructionQuantity','B101','新增工程量统计')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (3,'B10102','工程量统计修改','ConsturctionManager.UI.FrmConstructionQuantity','B101','修改工程量统计')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (3,'B10103','工程量统计删除','ConsturctionManager.UI.FrmConstructionQuantity','B101','删除工程量统计')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (3,'B10104','施工子项','ConsturctionManager.UI.FrmSubItem','B101','打开施工子项')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (4,'B1010401','新增施工子项','ConsturctionManager.UI.FrmSubItem','B10104','新增施工子项')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (4,'B1010402','更新施工子项','ConsturctionManager.UI.FrmSubItem','B10104','更新施工子项')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (4,'B1010403','删除施工子项','ConsturctionManager.UI.FrmSubItem','B10104','删除施工子项')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (4,'B1010404','打开附件图片','ConsturctionManager.UI.FrmItemImage','B10104','打开附件图片')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (5,'B101040401','新增附件图片','ConsturctionManager.UI.FrmItemImage','B1010404','新增附件图片')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (5,'B101040402','删除附件图片','ConsturctionManager.UI.FrmItemImage','B1010404','删除附件图片')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (4,'B1010405','打开附件文件','ConsturctionManager.UI.FrmSubItemFile','B10104','打开附件文件')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (5,'B101040501','新增附件文件','ConsturctionManager.UI.FrmSubItemFile','B1010405','新增附件文件')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (5,'B101040502','删除附件文件','ConsturctionManager.UI.FrmSubItemFile','B1010405','删除附件文件')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (3,'A10104','开工日期附件','ConstructionManagement.UI.FrmUploadFile','A101','打开开工日期附件')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (4,'A1010401','开工日期附件上传','ConstructionManagement.UI.FrmUploadFile','A10104','上传开工日期附件')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (4,'A1010402','开工日期附件删除','ConstructionManagement.UI.FrmUploadFile','A10104','删除开工日期附件')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (3,'A10105','施工前附件','ConstructionManagement.UI.FrmUploadFile','A101','打开施工前附件')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (4,'A1010501','施工前附件上传','ConstructionManagement.UI.FrmUploadFile','A10105','打开施工前附件')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (4,'A1010502','施工前附件删除','ConstructionManagement.UI.FrmUploadFile','A10105','打开施工前附件')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (3,'A10106','施工计划','ConstructionManagement.UI.FrmConstructionPlan','A101','打开施工前附件')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (4,'A1010601','新增施工计划','ConstructionManagement.UI.FrmConstructionPlan','A10106','打开施工前附件')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (4,'A1010602','修改施工计划','ConstructionManagement.UI.FrmConstructionPlan','A10106','打开施工前附件')
INSERT INTO MenuItem (OrderNo,ItemID,ItemName,ItemType,ParentId,Description) VALUES (4,'A1010603','删除施工计划','ConstructionManagement.UI.FrmConstructionPlan','A10106','打开施工前附件')
