
IF(OBJECT_ID('T_DEL_DICT','U') IS NOT NULL)
DROP TABLE T_DEL_DICT
GO
CREATE TABLE T_DEL_DICT(
ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NAME NVARCHAR(50) NOT NULL,
PHONE NVARCHAR(30),
PHONE1 NVARCHAR(30),
JOB_TITLE NVARCHAR(30),
COMPANY NVARCHAR(50),
REMARK NVARCHAR(100)
);